lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Models/EncyclopedyModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatarzynaKrawczykLab8Zad1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9B1FC5_cpc20181Entities1 : DbContext
    {
        public DB_9B1FC5_cpc20181Entities1()
            : base("name=DB_9B1FC5_cpc20181Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KatarzynaKrawczykEntries> KatarzynaKrawczykEntries { get; set; }
        public virtual DbSet<KatarzynaKrawczykImages> KatarzynaKrawczykImages { get; set; }
    }
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Models/EncyclopedyModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\frygt\Desktop\Kredek\katarzyna_krawczyk\lab8\KatarzynaKrawczykLab8Zad1\KatarzynaKrawczykLab8Zad1\Models\EncyclopedyModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Models/EncyclopedyModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Models/KatarzynaKrawczykEntries.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatarzynaKrawczykLab8Zad1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KatarzynaKrawczykEntries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KatarzynaKrawczykEntries()
        {
            this.KatarzynaKrawczykImages = new HashSet<KatarzynaKrawczykImages>();
        }
    
        public int Id { get; set; }
        public string Keyword { get; set; }
        public string Definition { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KatarzynaKrawczykImages> KatarzynaKrawczykImages { get; set; }
    }
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Models/KatarzynaKrawczykImages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatarzynaKrawczykLab8Zad1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KatarzynaKrawczykImages
    {
        public int Id { get; set; }
        public int IdEntry { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual KatarzynaKrawczykEntries KatarzynaKrawczykEntries { get; set; }
    }
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Controllers/KatarzynaKrawczykEntriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KatarzynaKrawczykLab8Zad1.Models;

namespace KatarzynaKrawczykLab8Zad1.Controllers
{
    public class KatarzynaKrawczykEntriesController : Controller
    {
        //próbowałam zmienić namespace, ale niesttey za każdym razem zostawała nazwa bazy danych i nie udalo mi się ego naprawić.
        private DB_9B1FC5_cpc20181Entities1 db = new DB_9B1FC5_cpc20181Entities1();

        // GET: KatarzynaKrawczykEntries
        public ActionResult Index(string word)
        {
            return View(db.KatarzynaKrawczykEntries.Where(x=> x.Keyword.Contains(word) || word ==null).ToList());
        }
        // GET: KatarzynaKrawczykEntries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KatarzynaKrawczykEntries katarzynaKrawczykEntries = db.KatarzynaKrawczykEntries.Find(id);
            if (katarzynaKrawczykEntries == null)
            {
                return HttpNotFound();
            }
            return View(katarzynaKrawczykEntries);
        }


        // GET: KatarzynaKrawczykEntries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KatarzynaKrawczykEntries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Keyword,Definition,Description")] KatarzynaKrawczykEntries katarzynaKrawczykEntries)
        {
            if (ModelState.IsValid)
            {
                db.KatarzynaKrawczykEntries.Add(katarzynaKrawczykEntries);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(katarzynaKrawczykEntries);
        }

        // GET: KatarzynaKrawczykEntries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KatarzynaKrawczykEntries katarzynaKrawczykEntries = db.KatarzynaKrawczykEntries.Find(id);
            if (katarzynaKrawczykEntries == null)
            {
                return HttpNotFound();
            }
            return View(katarzynaKrawczykEntries);
        }

        // POST: KatarzynaKrawczykEntries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Keyword,Definition,Description")] KatarzynaKrawczykEntries katarzynaKrawczykEntries)
        {
            if (ModelState.IsValid)
            {
                db.Entry(katarzynaKrawczykEntries).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(katarzynaKrawczykEntries);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Views/KatarzynaKrawczykEntries/Create.cshtml
@model KatarzynaKrawczykLab8Zad1.Models.KatarzynaKrawczykEntries

@{
    ViewBag.Title = "Create";
}
<div id="navbar" class="navbar_absolute">
    @using (Html.BeginForm("Index", "KatarzynaKrawczykEntries", FormMethod.Get))
    {
        @Html.TextBox("word")<input class="search-bar" type="submit" value="Search" />
    }
</div>
<div id="banner">
    <div id="title">
        <img id="banner-image" src="~/Content/Images/logoIcon.png" />
        Encyklopedia Dzikich Kotów
    </div>
</div>

<div class="container body-content">

    <div class="left-side">
        <p class="side-header">Twórzmy razem!</p>
        <p>
            @Html.ActionLink("Zacznij od początku", "Create")
        </p>
    </div>
    <div class="entries-list">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>KatarzynaKrawczykEntries</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Keyword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Definition, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Definition, new { cols = 35, @rows = 3, })
                        @Html.ValidationMessageFor(model => model.Definition, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { cols = 35, @rows = 3, })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="right-side">
        <p class="side-header">
            Podlej kwiatek!
        </p>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Views/KatarzynaKrawczykEntries/Details.cshtml
@model KatarzynaKrawczykLab8Zad1.Models.KatarzynaKrawczykEntries

@{
    ViewBag.Title = "Details";
}
<!-- powiększanie obraz - do poprawienia wersja z błędami-->
<div id="myModal" class="modal-hidden">
    <span class="close">&times;</span>
    <img id="modal-image" class="modal-content" src="~/Content/Images/lion.jpg" />
    <div id="caption"></div>
</div>

<!-- pasek z wyszukiwarką - zawsze zzostaje na górze strony-->
<div id="navbar" class="navbar_absolute">
    @using (Html.BeginForm("Index", "KatarzynaKrawczykEntries", FormMethod.Get))
    {
        @Html.TextBox("word")<input type="submit" value="Search" />
    }
</div>
<!-- górny pasek na stronie część na logo itp-->
<div id="banner">
    <div id="title">
        Encyklopedia Dzikich Kotów
    </div>
</div>
<!-- część użytkowa strony -->
<div class="container body-content">
    <!-- lewy pasek strony-->
    <div class="left-side">
        <p class="side-header">Twórzmy razem!</p>
        <p>
            @Html.ActionLink("Edytuj to hasło", "Edit", new { id = Model.Id })
        </p>
    </div>
    <!-- środkowy pasek strony - część główna -->
    <div class="entries-list">
        <!-- wybrane hasło-->
        <header class="keyword">
            @Html.DisplayFor(model => model.Keyword)
        </header>
        <!-- definicja hasła-->
        <p id="definition">
            @Html.DisplayFor(model => model.Definition)
        </p>
        <!-- opis hasła-->
        <p>
            @Html.DisplayFor(model => model.Description)
        </p>
        <header class="keyword">
                ilustracje
        </header>
        <!-- część na miniaturki ilustracji-->
        <div id="ilustrations">
            @foreach (var item in Model.KatarzynaKrawczykImages)
            {
                <div id="ilustration-thumbnail">
                    <img class="ilustration" onclick=enlargeImage() src="@Html.DisplayFor(modelItem => item.Image)"  alt="@Html.DisplayFor(modelItem => item.Description)"/>
                    <p id="ilustration-description">@Html.DisplayFor(modelItem => item.Description)</p>
                </div>
            }
        </div>
    </div>
    <!-- prawy pasek strony -->
    <div class="right-side">
        <p class="side-header">
            Podlej kwiatek!
        </p>
    </div>
</div>
<p>
    
    @Html.ActionLink("Back to List", "Index")
</p>
@Scripts.Render("~/Scripts/script.js")

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Views/KatarzynaKrawczykEntries/Edit.cshtml
@model KatarzynaKrawczykLab8Zad1.Models.KatarzynaKrawczykEntries
@{
    ViewBag.Title = "Edit";
}


<div id="navbar" class="navbar_absolute">
    @using (Html.BeginForm("Index", "KatarzynaKrawczykEntries", FormMethod.Get))
    {
        @Html.TextBox("word")<input class="search-bar" type="submit" value="Search" />
    }
</div>
<div id="banner">
    <div id="title">
        <img id="banner-image" src="~/Content/Images/logoIcon.png" />
        Encyklopedia Dzikich Kotów
    </div>
</div>

<div class="container body-content">

    <div class="left-side">
        <p class="side-header">Twórzmy razem!</p>
        <p>
            @Html.ActionLink("Dodaj nowe hasło", "Create")
        </p>
    </div>
    <div class="entries-list">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Edytuj hasło: @Html.DisplayFor(model => model.Keyword)</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    <label class = "control-label col-md-2" >Hasło:</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Keyword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Definicja:</label>
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Definition, new { cols = 35, @rows = 3 ,})
                        @Html.ValidationMessageFor(model => model.Definition, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Opis:</label>
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { cols = 35, @rows = 3 })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="right-side">
        <p class="side-header">
            Podlej kwiatek!
        </p>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Views/KatarzynaKrawczykEntries/Index.cshtml
@model IEnumerable<KatarzynaKrawczykLab8Zad1.Models.KatarzynaKrawczykEntries>

@{
    ViewBag.Title = "Index";
}
<!-- część z wyszukiwarką - pasekktóry zawsze jest u góry-->
<div id="navbar" class="navbar_absolute">
    @using (Html.BeginForm("Index", "KatarzynaKrawczykEntries", FormMethod.Get))
    {
        @Html.TextBox("word")<input class="search-bar" type="submit" value="Search" />
    }
</div>
<!-- część z bannerem - miejsce na logo itp-->
<div id="banner">
    <div id="title">
        <img id="banner-image" src="~/Content/Images/logoIcon.png"  />
        Encyklopedia Dzikich Kotów
    </div>
</div>
<!-- część użytkowa strona-->
<div class="container body-content">
    <!-- lewy pasek strony -->
    <div class="left-side">
        <p class="side-header">Twórzmy razem!</p>
        <p>
            @Html.ActionLink("Dodaj nowe hasło", "Create")
        </p>
    </div>
    <!-- środkowy pasek strony - główny-->
    <div class="entries-list">
        <h2>Gatunki:</h2>
        <!-- tabela z hasłami-->
        <table>
            <tr>
                <th>
                    <p>Lista dostępnych haseł:</p>
                </th>
            </tr>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td>
                        Nie odnaleziono hasła.
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                <tr>
                    <td id="item" style="padding-top:5px; padding-bottom:5px;">
                        @Html.ActionLink(@Html.DisplayFor(modelItem => item.Keyword).ToString(), "Details", new { id = item.Id })
                    </td>
                </tr>
                }
            }

        </table>
    <!-- prawy pasek strony -->
    </div>
    <div class="right-side">
        <p class="side-header">
            Podlej kwiatek!
        </p>
    </div>
</div>
@Scripts.Render("~/Scripts/cookiesScript.js")

lab8/KatarzynaKrawczykLab8Zad1/KatarzynaKrawczykLab8Zad1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/style.css")
    @Scripts.Render("~/Scripts/script.js")
</head>
<body onload="javascript:window_onload();">
    <div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>